// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqHsSEMgV_Y3v8GN5Zj18LICi2EaW94-U',
    appId: '1:452014915095:web:c2650ddd457588d37ee652',
    messagingSenderId: '452014915095',
    projectId: 'projeto-programacao-movel',
    authDomain: 'projeto-programacao-movel.firebaseapp.com',
    databaseURL: 'https://projeto-programacao-movel-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-programacao-movel.appspot.com',
    measurementId: 'G-ELHWR04KCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrAQxP5ad9lg43vrAD0c0LS72R95YGpzQ',
    appId: '1:452014915095:android:e2c4f30933818b5c7ee652',
    messagingSenderId: '452014915095',
    projectId: 'projeto-programacao-movel',
    databaseURL: 'https://projeto-programacao-movel-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-programacao-movel.appspot.com',
  );
}
